'This is the first Program I ever wrote. A portion of it was upgraded by my
'dad and I also did a bit of work on it i fixed the bug error so you
'cant come back where you died any more type in the word that describes
'where to go and if it doesn't work try another word be sure that caps lock
'is on  this is version 1.4
KEY OFF: SCREEN 0, 1
 COLOR 1, 7

 CLS
71 PRINT : PRINT : PRINT "          Hello!  I am the tunnel master."
 PRINT : PRINT "          Do you want to play a game?"
 PRINT : PRINT "          You have no choice!"
 PRINT : PRINT "          What is your name?"
 INPUT A$
 PRINT : PRINT "          "; A$, "that's a good name."
 PRINT : PRINT "          You head into an old castle."
 PRINT : PRINT "          You see three doors.  You try the wooden one, but it's locked."
 PRINT : PRINT "          Do you want to open the brass door or the gold door?"
 PRINT : PRINT : PRINT "               Type B for brass door."
 PRINT : PRINT "               Type G for gold door."
 INPUT A$
 CLS
 PRINT : PRINT : PRINT :
 IF A$ = "g" GOTO 140
 IF A$ = "G" GOTO 140
 IF A$ = "b" GOTO 180
 IF A$ = "B" GOTO 180
GOTO 71
140 PRINT "          You open the gold door.  You see two tunnels."
 PRINT : PRINT "          Do you want to go down the left tunnel or the right tunnel?"
 PRINT : PRINT : PRINT "               Type L for left."
 PRINT : PRINT : PRINT "               Type R for right."
 INPUT A$
 IF A$ = "R" GOTO 780
 IF A$ = "L" GOTO 610
 IF A$ = "r" GOTO 780
 IF A$ = "l" GOTO 610
 CLS
GOTO 140
180 PRINT : PRINT : PRINT :
 PRINT "          You open the brass door and see a monster.  Do you fight?"
 PRINT : PRINT : PRINT "               Type F for fight."
 PRINT : PRINT : PRINT "               Type N to go on."
 INPUT A$
 CLS
 PRINT : PRINT : PRINT :
 IF A$ = "F" GOTO 220
 IF A$ = "f" GOTO 220
 IF A$ = "N" GOTO 260
 IF A$ = "n" GOTO 260
GOTO 180
220 PRINT "          You think you can beat the monster, but you're wrong."
 PRINT : PRINT : PRINT :
230 PRINT "          The monster kills you easily."
 PRINT : PRINT : PRINT "               Play again?  Y or N"
 INPUT A$
 IF A$ = "Y" GOTO 71
 IF A$ = "y" GOTO 71
 IF A$ = "N" GOTO 600
 IF A$ = "n" GOTO 600
GOTO 230
260 PRINT "YOU CANT WIN THE MONSTER HIDE BEHIND BOX OR DESK"
 INPUT A$
 IF A$ = "DESK" GOTO 301
 IF A$ = "BOX" GOTO 330
  GOTO 260
301 PRINT "YOU HIDE BEHIND THE DESK NOT A WISE CHOICE THE MONSTER"
 PRINT "COMES AND RIPS YOU TO PEECES"
 PRINT : PRINT : PRINT "               Play again?  Y or N"
 INPUT A$
 IF A$ = "Y" GOTO 71
IF A$ = "y" GOTO 71
 IF A$ = "N" GOTO 600
 IF A$ = "n" GOTO 600
GOTO 301
330 PRINT "YOU HIDE BEHIND A BOX THE MONSTER DOESNT SEE YOU"
 PRINT "YOU HVE TO GET OUT OF THE ROOM SO YOU CRAWL"
 PRINT "THROUGH THE VENTALATION SYSTEM YOU COME TO A LEFT AND RIGHT SHAFT"
 PRINT "GO LEFT OR RIGHT"
 INPUT A$
 IF A$ = "RIGHT" GOTO 390
 IF A$ = "LEFT" GOTO 450
GOTO 330
390 PRINT " YOU GO Right CAUSE RIGHT IS THE RIGHT COICE THIS TIME IT ISNT"
 PRINT "YOU BURN FROM HEAT EXAUGHTON PLAY AGAIN Y OR N"
 INPUT A$
 IF A$ = "Y" GOTO 71
 IF A$ = "N" GOTO 600
GOTO 390
450 PRINT " YOU GO LEFT YOU SOON LEAVE THE VENT"
 PRINT "YOU SEE A MONSTER ABOUT TO EAT A PRINCESS"
 PRINT "WHAT DO YOU DO YELL OR TRY TO FIGHT"
 INPUT A$
 IF A$ = "YELL" GOTO 510
 IF A$ = "FIGHT" GOTO 550
       GOTO 450
510 PRINT "YOU YELL FOR THE MONSTER HE COMES HE EATS YOU AND THE PRINCESS"
 PRINT "PLAY AGAIN Y OR N"
 INPUT A$
 IF A$ = "Y" GOTO 71
 IF A$ = "N" GOTO 600
GOTO 510
550 PRINT "YOU FIGHT AND WIN"
 PRINT "THE HEART OF THE PRINCESS HAS BEEN WON"
 PRINT "YOU AND THE PRINCESS KISS YOU LOVE THE PRINCEESS YOU KEEP KISSING "
 PRINT "AND KISSING YOU LOVE EACH OTHER SO MUCH"
600 PRINT "YOU WIN"
 PRINT "WIN LOSE DOESNT MATTER"
 END
610 PRINT "YOU GO LEFT YOU BUMP INTO A AX PICK IT UP Y OR N"
 INPUT A$
 IF A$ = "N" GOTO 660
 IF A$ = "Y" GOTO 1110
GOTO 610
660 PRINT " YOU DONT PICK IT UP BUT IT SWINGS UP AND CHOPS YOU IN TWO"
 PRINT " PLAY AGAIN Y OR N"
 INPUT A$
 IF A$ = "Y" GOTO 71
 IF A$ = "N" GOTO 600
GOTO 660
780 PRINT "YOU GO RIGHT THATS A GOOD CHOICE "
 PRINT "YOU KEEP WALKING AND YOU COME TO A BABE"
 PRINT "SHE WANTS TO KISS YOU KISS HER Y OR N"
 INPUT A$
 IF A$ = "Y" GOTO 840
 IF A$ = "N" GOTO 890
GOTO 780
840 PRINT "YOU KISS HER SHE TURNS INTO A MONSTER"
 PRINT "AND BITES YOU HEAD OFF PLAY A GAIN Y OR N"
 INPUT A$
 IF A$ = "N" GOTO 600
 IF A$ = "Y" GOTO 71
GOTO 840
890 PRINT " YOU FEEL YOUR TO YOUNG TO KISS HER BUT"
 PRINT "SHE SAYS SHE IS IN TROUBLE SO YOU RESCUE HER"
 PRINT "YOU LEAVE THE CASTLE AND WALK INTO A VALLEY"
 PRINT "SHE ASKS TO MARRY YOU Y OR N"
 INPUT A$
 PRINT "NO CHOICE YOU CANT MARRY HER"
 PRINT "YOU TWO COME TO A ROAD THAT LEADS INTO A CITY"
 PRINT "AND A ROAD THAT LEADS TO THE COUNTRY"
 PRINT "YOU GO TO THE CITY AND THE BABE GOES TO THE COUNTRY"
 PRINT "YOU WALK INTO A VIDEO ARCADE"
 PRINT "WHAT GAME DUKE NUKEM OR RASHERS"
 INPUT A$
 IF A$ = "DUKE NUKEM" GOTO 1040
 IF A$ = "RASHERS" GOTO 1090
GOTO 890
1040 PRINT "YOU CHOOSE DUKE NUKEM IT BLOWS UP YOUR IN A HOSPITOL"
 PRINT "PLAY AGAIN Y OR N"
 INPUT A$
 IF A$ = "Y" GOTO 71
 IF A$ = "N" GOTO 600
1090 PRINT " YOU CHOOSE RASHERS RASHERS ITS FUN YOU "
 PRINT " YOU WIN THE GAME YOU PLAY VIDEO GAMES FOR THE REST OF YOUR LIFE"
 END
1110 PRINT "YOU PICK UP THE AX AND MOVE ON"
 PRINT "SOON YOU COME TO AN UP OR DOWN SHAFT GO UP OR DOWN"
 INPUT A$
 IF A$ = "DOWN" GOTO 1160
 IF A$ = "UP" GOTO 1210
GOTO 1110
1160 PRINT "YOU GO DOWN BUT THE ROPE BRAKS YOU FALL TO YOUR DEATH"
 PRINT "PLAY AGAIN Y OR N"
 INPUT A$
 IF A$ = "Y" GOTO 71
 IF A$ = "N" GOTO 600
GOTO 1160
1210 PRINT "YO CLIMB UP A LADDER SOON YOU COME TO A PASSAGE"
 PRINT "YOU SEE A MONSTER DO YOU WANT TO FIGHT IT WITH YOUR AX Y OR N"
 INPUT A$
 IF A$ = "N" GOTO 1260
 IF A$ = "Y" GOTO 1300
GOTO 1210
1260 PRINT "YOU DONT FIGHT IT BUT HE FIGHTS YOU YOUR DEAD PLAY AGAIN Y OR N"
 INPUT A$
 IF A$ = "Y" GOTO 71
 IF A$ = "N" GOTO 600
GOTO 1260
1300 PRINT "YOU FIGHT IT AND WIN EASILY SO YOU GO ON"
 PRINT " SOON ENOUGH YOU COME TO A FLOATING BARRICADE"
 PRINT "GO UNDER OR OVER"
 INPUT A$
 IF A$ = "UNDER" GOTO 1370
 IF A$ = "OVER" GOTO 1410
GOTO 1300
1370 PRINT "YOU GO UNDER THE BARRICADE SMASHES YOU PLAY AGAIN Y OR N"
 INPUT A$
 IF A$ = "Y" GOTO 71
 IF A$ = "N" GOTO 600
GOTO 1370
1410 PRINT "YOU CLIMB OVER IT AND YOUR ON THE OTHER SIDE"
 PRINT " YOU WALK OUT INTO FRESH AIR YOU MEET A DWARF"
 PRINT "WANT TO KILL IT"
 INPUT A$
 PRINT "TOO BAD YOU CANT KILL HIM"
 PRINT "HE TAKE YOU TO AN ARCADE WHAT GAME DUKE NUKEM OR RASHERS "
INPUT A$
 IF A$ = "RASHERS" GOTO 1090
 IF A$ = "DUKE NUKEM" GOTO 1040
 GOTO 1410

